cups = [
    """Ace of Cups -   The Ace of Cups in your present situation suggests that you are experiencing a wellspring of emotions, especially love. Perhaps you are in the process of finding a new love interest, or discovering renewed feelings in a relationship you already have. The dove, representative of spiritual love, symbolizes the depth to which this emotional renewal is touching you. It has given you a new emotional perspective. The water flowing from the cup suggests that your emotional being (represented by the water below) is becoming recharged from this outpouring. """,
    """Two of Cups -   Love and deep friendship are suggested by the Two of Cups. You may be in the process of entering into a fulfilling love relationship. This union is based on passion and strength, symbolized by the lion, and a healthy attitude, suggested by the Caduceus, or wand of medicine. The man and woman facing each other, staring into one anotherƒ??s eyes, suggest the deeper sense of understanding that exists between them. You are probably feeling understanding with this person that you have felt with few others. Perhaps marriage is on the way. """,
    """Three of Cups -   The Three of Cups indicates the celebration of friendship, and the joy of being together. You are enjoying time with close friends and remembering the good times that you have shared. Great achievements are toasted among you, suggested by the bountiful harvest at the feet of the women celebrating. This is a time of appreciation of the deeper sense of understanding that you share with your closest friends. It is said that we find few true friends in our lifetime. Treasure yours always. """,
    """Four of Cups -   The Four of Cups indicates a strong sense of emotional retreat and discontent that you are experiencing. The man sitting against the tree seems to be closed off to new ideas. You may be focusing on the boredom youƒ??ve been feeling with what you already have, suggested by the three cups at the manƒ??s feet. A new opportunity is being offered you and you may be turning it down, deciding instead to close yourself off. Perhaps you are in need of this retreat, and need to evaluate whatƒ??s important to you, but spending too long in this mode can prevent you from moving forward. """,
    """Five of Cups -   The Five of Cups suggests that you are upset over a loss or disappointment. The three cups spilled at the manƒ??s feet in the picture indicate the loss youƒ??re experiencing. You may not be aware of the strong support system that remains, indicated by the two cups still standing. Your friends and loved ones are offering their support but you are focusing too much on the disappointment. The river in the image suggests the troubled emotions that are making you feel lost and distant you are cutting yourself off from the joy and love associated with home. Remember to notice the bridge that isnƒ??t far from view. It can lead you home again, into the arms of your loved ones. """,
    """Six of Cups -   Childhood memories, family gatherings, and friends from the past are all suggested by the Six of Cups. You may be about to encounter a friend or lover from your past that you havenƒ??t seen in many years, if you havenƒ??t already bumped into this person. The child bearing the flowering cup indicates the positive nature of this meeting. The pleasant home in the background is also a strong indicator of family and home. You may be spending more time with family and old friends. Celebrate your past. It is the foundation for your dreams and goals in the future. """,
    """Seven of Cups -   Flights of fancy and daydreaming are indicated by the Seven of Cups. In the picture we see the many visions of happiness that the character sees in the cups, but they are all unrealistic goals at this time: a castle in the clouds, jewels, dragons, and holy figures, among others. You may be experiencing a preoccupation with visions of fantastic goals as a means of escaping an emotional reality you arenƒ??t able to confront. There are real and tangible sources of happiness in your life and those are the things you should treasure. Open up to the love around you. """,
    """Eight of Cups -   The Eight of Cups suggests that you are beginning an important journey of self-exploration. The cups the character in the picture is leaving behind seem organized and stable, though there is a noticeable gap in them. This shows that you have a relatively stable situation that you are leaving behind, but that you feel that there is something more, something your soul is seeking. The moon is shown eclipsing the sun which shows how your search for deeper meaning is blocking out the importance of ordinary daily life. You must climb the mountain to find your spiritual peak. It is said that the journey of a thousand miles begins with one step. """,
    """Nine of Cups - Enjoying the fulfillment of desire is indicated by the Nine of Cups. You may be in a place in your life where you are comfortable and happy, and are able to enjoy the many rewards of your past actions. Contentment and luxury are suggested by the imagery of the man, sitting comfortably, enjoying the nine cups arranged on the banquet table. Life is your banquet, and youƒ??ve earned the right to enjoy it. In old tradition, the Nine of Cups is the Wish Card"" and was always thought to mean the fulfillment of oneƒ??s innermost desires. """,
    """Ten of Cups -   The Ten of Cups suggests the success of family and emotional fulfillment. The rainbow is the promise of stability and protection, and in the Bible, the rainbow was used as Godƒ??s promise that he would never again send a flood of destruction to the earth. You may be in the process of realizing how strong your family is, and what they have done to help create who you are and give you strength. Your current family, if you have one, is growing closer, perhaps after a very trying time. This card can also signify the start of a new family, like a young tree sending its first roots into the ground. """,
]
