swords = [
    """Ace of Swords -   In the Ace of Swords, the crowned sword of intellect is held over the mountains, literally denoting the triumph of mind over matter. Truth and honesty prevail, symbolized by the palm of victory, and peace is found, symbolized by the olive branch. Violent acts of force are not necessary to achieve your goals. Your determination and strength of Will have surmounted the obstacles in your path. """,
    """Two of Swords -   The Two of Swords symbolizes a choice. The decision is put off, and the seeker is stuck, unable to face the truth. The blindfold she wears willingly shows her inability to open her eyes to reality. She has chosen to turn away from her intuition and emotions, symbolized by the ocean. She is a passive participant, crossing her arms over her chest to protect her heart. Putting this decision off may buy you time to gain control over your emotions, but the decision will inevitably have to be made, and if you wait, it may be made for you. """,
    """Three of Swords -   One of the most disquieting cards of the Tarot is the Three of Swords. The images show three swords penetrating the heart, which implies that you may be going through a state of intense sorrow. This card shows separation, divorce, and perhaps even the harmful intrusion of a third party, as in an extramarital affair. The falling rain seems to enhance the dismal nature of this card, but fear not. From the fall of rain comes growth. You will become stronger from this experience, and your own inner love will shine through. """,
    """Four of Swords -   The Four of Swords represents an inner retreat that you are currently taking. Your present situation is very difficult and you may be in the midst of much turmoil. A temporary truce seems to be in place, and you are now seeking recuperation within. The swords on the wall symbolize your previous battles, and the sword at your side represents your current conflict. You will soon take up the sword again. The battle isn??t over, but when you return to it, you??ll be invigorated and able to formulate a mature, effective response. When combined with the Eight of Wands or the Six of Swords, this card can also mean that some kind of an actual trip may take place, one intended to bring you peace of mind. """,
    """Five of Swords -   The Five of Swords indicates defeat. You may have just lost a battle (most likely a mental one), and find yourself in retreat, seeking to calm the choppy waters of your emotions. The character collecting the swords suggests that a score-keeper, motivated by revenge and vindication, is at the heart of your troubles. This card can also be a warning to you to avoid your own lusts for revenge, showing that only hurt and pain will be the result. Take time to heal your wounds. Concede your defeat and find new things to focus on. """,
    """Six of Swords -   The Six of Swords represents a retreat that you are in the process of taking. You have been dealing with heavy stress, signified by the choppy water behind the boat. This card can also indicate that you feel ??haunted? by someone or something, and you seek closure. You are in the process of leaving this behind, setting forth for the calmness of still waters. You are learning to balance your mental state, evidenced by the swords that do not fall though the boat is in motion. You are also the protector in the situation. Your loved ones are relying on you to carry them away from troubled waters. You won??t let them down. """,
    """Seven of Swords -   The aggressor in the Seven of Swords slyly makes off with many of his enemy??s weapons, taking his opposition down a peg in an underhanded way. He cannot defeat the competition completely this way: some swords remain, evidence that the war is not over yet. He acts alone, indicating that your present situation is a somewhat clandestine one. The warning here is not to get too wrapped up in mental games, one-upmanship, and petty battles that do not solve anything. Take the high road. """,
    """Eight of Swords -   Oppression is symbolized by the Eight of Swords. You may be feeling trapped and alone, unable to see your way through to a solution. The castle in the background suggests the authority figure that you may feel is keeping you down. The swords are the opposition that is keeping you where you are. Look closer. Could you be keeping yourself there? Notice that the woman in the picture does not have her feet tied, nor are the swords blocking her way. You have been free to go all along. The oppressor in your life may actually be real, but you must not give away your power. You may be feeling that it??s time to move on. Trust your inner voice. """,
    """Nine of Swords -   The depth of mental anguish felt by the person in the Nine of Swords is beyond description. The carving on the bed shows the violence that led to the current situation, and suggests that someone you love may have been involved in the battle. The swords on the wall indicate that you have not been struck directly at this time. Sleepless nights, anxiety dreams, and worry plague you: note that the person sits up, head in hands, crying alone in bed. This body language epitomizes guilt, depression, and despair. There is a need for comfort, emotional shelter, forgiveness, and healing. """,
    """Ten of Swords -   The swords stuck in the person??s back symbolize failed plans, loss, and defeat, but the sheer number of swords, ten, can indicate over-dramatization of the situation. It probably is not as bad as it seems to the one who is in it. The water is calm, the sky on the horizon is light, and it is the darkest hour that is passing. Soon, the dawn will come, and a new beginning with it, so do not lose hope. """,
]
