wands = [
    """Ace of Wands -   All that is best in the suit of Wands is embodied in the Ace: the power of Will, desire, sexuality, and vitality are abundant at this time. Just as the leaves burst forth with such force that they are seen falling from the Wand, your energy brings forth many fertile beginnings. This card symbolizes the healthy, positive outlook that should be held in the present situation. Great things are indicated. """,
    """Two of Wands -   The Two of Wands represents opportunity, especially in business. Perhaps you are in the process of laying the foundation for a new venture. You have achieved some success, indicated by the wand fastened securely to the castle wall. Also note the lilies of purity balanced by the red roses of desire. This shows the balance with which you approach your goal. The wand in one hand represents your undertaking and the globe in the other suggests the tremendous potential for success. The character in the image, looking out to sea, suggests trade and could indicate strong partnerships and alliances. You are in the early stages of a prosperous enterprise. """,
    """Three of Wands -   The person depicted in the Three of Wands sends his ships out, staying behind to ??hold the fort?. This card can indicate the desire to maintain existing relationships while testing the waters of new ones. In business terms, this is job hunting while you are still gainfully employed  in matters of love, this can indicate the desire to have an affair. Ponder the needs you are looking to fill with whatever you are seeking. """,
    """Four of Wands -   The successful completion of projects is indicated by the Four of Wands. The garland hanging from the four wands suggests that your goals were recently achieved. The castle represents the solidity and splendor of what you have created. The characters in the image hold the harvest of their efforts high in the air in celebration of their success. Enjoy the well-earned fruits of completion. """,
    """Five of Wands -   Healthy competition is indicated by the Five of Wands. Notice that nobody in the picture is causing harm to another. They are all simply vying for position. This card indicates that you could be in the position for success in business or in the workplace, but that competition could be slowing you down. Are you spending too much time on the weaknesses of others, rather than amplifying your own strengths and good qualities? Competition can often be good and force you to perform at your best level, but don't let it become an obsession for its own sake. """,
    """Six of Wands -   Some congratulations are in order when this card appears! You are being crowned with the wreath of victory on some level, and while the end is not here yet, you are still riding high on your achievement. Your belief in yourself is renewed, and others are inspired by your success. Note how the crowd in the card seems to line the street as the man rides through them on his horse: those around you support your efforts, and celebrate your triumph with you. Take a bow! """,
    """Seven of Wands -   The Seven of Wands is a card of defense and confrontation. You have been forced to face a conflict head on. You are cornered and have no choice but to confront the source of the present turmoil. While you are successful and respected, there are those around you who would seek to knock you off your throne of position. Your only choices are to forfeit what you've worked for or to fight. Wands represent passion and fire and these are what you feel for your position and what you've accomplished. Use your vantage point at the top of the mountain to strategically plot your next move. This is not a time for compromise. You must adhere to your deeply held beliefs if you want to succeed in the battle. """,
    """Eight of Wands -   Swiftness, closure, and the end of opposition are symbolized by the Eight of Wands. The wands pointing downward, toward the lush green earth, shows you reaching your destination successfully. Sometimes this card can be quite literal, indicating that are completing a trip by air. However, most often it signifies the successful and speedy completion of a goal. """,
    """The Nine of Wands indicates a pause, a time to ?wait and see.? You have seen many battles relating to your situation, and you have fought hard. Like the man in the card whose head is bandaged but unbowed, your Will shall remain intact. These conflicts have strengthened you, but they have hardened you, making you better able to weather life's struggles, but at what price? Be aware of your defenses and when they are triggered...they may make you seem unapproachable. Someone will try to earn your trust, which is hard won at best. Don't pick fights, or see trouble where there isn't any; you can keep your thick skin, but don't build walls. In the end, you will only block yourself if you do.""",
    """Ten of Wands -   Depicting a person over-burdened by a heavy load, the Ten of Wands indicates that you have a lot of irons in the fire??be careful not to get burned! You may be overextending yourself. Though you typically enjoy being busy, it may be time to delegate if possible to reduce your stress and give you more time to enjoy a taste of freedom. Choose your challenges wisely, and you will be able to give more of yourself to them. """,
]
